- name: create geonetwork user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ geonetwork_dbuser }} password={{ geonetwork_dbpass }}

- name: create geonetwork database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ geonetwork_dbname }} owner={{ geonetwork_dbuser }} template=template0 encoding=UTF8

- name: check if postgis is already loaded
  sudo: yes
  sudo_user: postgres
  command: psql -d {{ geonetwork_dbname }} -t -c "\dT"
  register: loaded_types

- name: create postgis extension for spatialindex
  sudo: yes
  sudo_user: postgres
  command: psql -d {{ geonetwork_dbname }} -t -c "CREATE EXTENSION postgis;"
  when: "loaded_types.stdout is defined and 'geometry' not in loaded_types.stdout"

