- name: create geonetwork user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ geonetwork_dbuser }} password={{ geonetwork_dbpass }}

- name: check if geonetwork schema already exists
  sudo: yes
  sudo_user: postgres
  command: psql -d {{ georchestra_dbname }} -t -c "\dn"
  register: loaded_schemas

- name: create geonetwork schema in georchestra db
  sudo: yes
  sudo_user: postgres
  command: psql -d {{ georchestra_dbname }} -c 'CREATE SCHEMA {{ geonetwork_schema }}'
  when: "loaded_schemas.stdout is defined and '{{ geonetwork_schema }}' not in loaded_schemas.stdout"

- name: grant all privileges to geonetwork user on its schema
  sudo: yes
  sudo_user: postgres
  postgresql_privs:
    database: "{{ georchestra_dbname }}"
    privs: ALL
    type: schema
    roles: "{{ geonetwork_dbuser }}"
    objs: "{{ geonetwork_schema }}"
