- name: installing apache2
  apt: pkg=apache2 state=installed

- name: enable required modules
  apache2_module: name={{ item }} state=present
  with_items: [proxy_ajp, proxy_connect, proxy_http, proxy, ssl, rewrite, headers]
  notify: reload apache2

- name: disable the default site
  file: path=/etc/apache2/sites-enabled/{{ item }} state=absent
  with_items: [000-default, default-ssl]
  notify: reload apache2

- name: template georchestra vhost
  template: src=georchestra.j2 dest=/etc/apache2/sites-available/georchestra

- name: enable georchestra vhost
  file: dest=/etc/apache2/sites-enabled/georchestra src=/etc/apache2/sites-available/georchestra state=link owner=root group=root mode=0644
  notify: reload apache2

- name: create web directories
  file: name={{ item }} state=directory
  with_items:
    - /var/www/georchestra/
    - /var/www/georchestra/conf/
    - /var/www/georchestra/ssl/

- name: create logs directories
  file: name=/var/www/georchestra/logs/ state=directory group=www-data mode=775

- name: clone htdocs dir
  git: repo=git://github.com/georchestra/htdocs.git dest=/var/www/georchestra/htdocs/ version=master

- name: fetch 50x.html error page
  get_url: dest=/var/www/georchestra/htdocs/errors/50x.html url=http://sdi.georchestra.org/errors/50x.html

- name: template config fragments
  tags: apache_config
  template: src={{ item.src }}.conf.j2 dest=/var/www/georchestra/conf/{{ item.dest }}.conf
  with_items:
  - { src: global, dest: global }
  - { src: common, dest: proxy, port: 8180 }
  - { src: common, dest: _static, port: 8180 }
  - { src: common, dest: cas, port: 8180 }
  - { src: common, dest: catalogapp, port: 8380 }
  - { src: common, dest: analytics, port: 8380 }
  - { src: common, dest: downloadform, port: 8380 }
  - { src: common, dest: extractorapp, port: 8380 }
  - { src: common, dest: geonetwork, port: 8380 }
  - { src: common, dest: geoserver, port: 8280 }
  - { src: common, dest: geofence, port: 8280 }
  - { src: common, dest: geowebcache, port: 8280 }
  - { src: common, dest: header, port: 8380 }
  - { src: common, dest: ldapadmin, port: 8380 }
  - { src: common, dest: mapfishapp, port: 8380 }
  notify: reload apache2

- name: generate self-signed cert
  command: >
    openssl req -new -nodes -x509 -subj "/C=FR/L=Somewhere/O=IT/CN={{ georchestra_fqdn }}"
      -days 3650 -keyout /var/www/georchestra/ssl/georchestra.key -out /var/www/georchestra/ssl/georchestra.crt -extensions v3_ca
    creates=/var/www/georchestra/ssl/georchestra.crt

- name: fix perms on certificate
  file: path=/var/www/georchestra/ssl/georchestra.key mode=0400
