- name: clone addons repository
  git: repo=https://github.com/GFI-Informatique/addons dest=/srv/gfi-addons version=dev

- name: create temp dir for cadastrapp
  file: name={{ cadastrapp_tmpdir }} owner=tomcat8 state=directory

- name: copy cadastrapp to mapfishapp/app/addons
  synchronize: src=/srv/gfi-addons/cadastrapp dest={{ tomcat_basedir }}/georchestra/webapps/mapfishapp/app/addons/ delete=yes
  delegate_to: test
