- name: remove wars
  file: path=/tmp/{{ item.key }}.war state=absent
  with_dict: georchestra_wars
# roles/tomcat/tasks/clean.yml already removed the unzipped wars & config

- name: remove datadirs
  file: path={{ item }} state=absent
  with_items:
  - "{{ geonetwork_datadir }}"
  - "{{ geoserver_datadir }}"
  - "{{ geowebcache_datadir }}"
  - "{{ extractor_datadir }}"
  - "{{ georchestra_datadir }}"

- name: remove non-free and contrib for dependencies
  apt_repository: repo="deb http://ftp.fr.debian.org/debian/ wheezy main non-free contrib" state=absent
