- name: template config files
  template:
    src: "{{ item.war }}/{{ item.file }}.j2"
    dest: /srv/tomcat/{{ georchestra_wars[item.war]['tomcat'] }}/webapps/{{ item.war }}/{{ item.destdir }}/{{ item.file }}
    backup: yes
#  debug: var=item
  with_items:
  - { file: proxy-servlet.xml, war: ROOT, destdir: 'WEB-INF' }
  - { file: security-proxy.properties, war: ROOT, destdir: 'WEB-INF' }
  - { file: log4j.properties, war: ROOT, destdir: 'WEB-INF/classes' }
  - { file: cas.properties, war: cas, destdir: 'WEB-INF' }
  - { file: log4j.xml, war: cas, destdir: 'WEB-INF/classes' }
  - { file: casGenericSuccess.jsp, war: cas, destdir: 'WEB-INF/view/jsp/default/ui' }
  - { file: ldapadmin.properties, war: ldapadmin, destdir: 'WEB-INF/spring' }
  - { file: log4j.properties, war: ldapadmin, destdir: 'WEB-INF/classes' }
  - { file: log4j.properties, war: geowebcache, destdir: 'WEB-INF/classes' }
  - { file: gwc.properties, war: geowebcache, destdir: 'WEB-INF/classes' }
  - { file: log4j.properties, war: geonetwork, destdir: 'WEB-INF/classes' }
  - { file: config-security.properties, war: geonetwork, destdir: 'WEB-INF' }
  - { file: config-overrides-georchestra.xml, war: geonetwork, destdir: 'WEB-INF' }
  notify: restart all tomcats

- name: fix broken webmvc-config.xml
  lineinfile: dest=/srv/tomcat/georchestra/webapps/ldapadmin/WEB-INF/spring/webmvc-config.xml regexp='org.postorg.postgresql.Driver' line='<property name="driverClassName" value="org.postgresql.Driver" />'
