- name: checkout geoserver datadir
  sudo: yes
  sudo_user: tomcat6
  git: repo=https://github.com/georchestra/geoserver_minimal_datadir.git dest={{ geoserver_datadir }}

- name: fix geoserver logging path
  sudo: yes
  sudo_user: tomcat6
  lineinfile: dest={{ geoserver_datadir }}/logging.xml regexp='<location>logs/geoserver.log</location>' line='  <location>{{ logs_basedir }}/geoserver.log</location>'

- name: set full geoserver url for getcapabilities docs
  sudo: yes
  sudo_user: tomcat6
  lineinfile: dest={{ geoserver_datadir }}/global.xml insertafter='<onlineResource>http://geoserver.org</onlineResource>' line='    <proxyBaseUrl>http://{{ georchestra_fqdn }}/geoserver</proxyBaseUrl>'

- name: set list of advertised wms srs
  sudo: yes
  sudo_user: tomcat6
  lineinfile: dest={{ geoserver_datadir }}/wms.xml insertafter='</metadata>' line="<srs><string>{{ geoserver_wms_srslist|join('</string><string>') }}</string></srs>"

# alternative could be to checkout the geofence branch of geoserver_minimal_datadir
- name: enforce geofence auth
  sudo: yes
  sudo_user: tomcat6
  lineinfile:
    dest: '{{ geoserver_datadir }}/security/auth/default/config.xml'
    regexp: '  <className>org.geoserver.security.auth.UsernamePasswordAuthenticationProvider</className>'
    line: '  <className>it.geosolutions.geoserver.authentication.auth.GeofenceAuthenticationProvider</className>'

- name: create geowebcache datadir
  file: dest={{ geowebcache_datadir }} owner=tomcat6 state=directory

- name: enable non-free and contrib for dependencies
  apt_repository: repo="deb http://ftp.fr.debian.org/debian/ wheezy main non-free contrib"

- name: install runtime dependencies
  apt: pkg={{ item }} state=installed
  with_items:
  - gdal-bin
  - ttf-mscorefonts-installer
  - libjai-imageio-core-java

- name: symlink jai libs to tomcat libdir
  file: src=/usr/share/java/{{ item[0] }}.jar dest={{ tomcat_basedir }}/{{ item[1] }}/lib/{{ item[0] }}.jar state=link
  with_nested:
  - [jai_imageio, jai_codec, mlibwrapper_jai, jai_core, clibwrapper_jiio]
  - [ georchestra, geoserver ]
