- name: create toplevel datadirs
  tags: wars
  file: path=/srv/{{ item }} state=directory owner=tomcat6 group=tomcat6
  with_items:
  - data
  - log

- include: wars.yml tags=wars
- include: geoserver.yml tags=geoserver
- include: geonetwork.yml tags=geonetwork
- include: config.yml tags=config
