- name: enable non-free and contrib for dependencies
  apt_repository: repo="deb http://ftp.fr.debian.org/debian/ wheezy main non-free contrib"

- name: install runtime dependencies
  apt: pkg={{ item }} state=installed
  with_items:
  - ttf-mscorefonts-installer
  - libjai-imageio-core-java

- name: symlink jai libs to tomcat libdir
  file: src=/usr/share/java/{{ item[0] }}.jar dest={{ tomcat_basedir }}/{{ item[1] }}/lib/{{ item[0] }}.jar state=link
  with_nested:
  - [jai_imageio, jai_codec, mlibwrapper_jai, jai_core, clibwrapper_jiio]
  - [ georchestra, geoserver ]

- name: add c2c repo gpg key
  apt_key: url=http://pkg.camptocamp.net/packages-c2c-key.gpg

- name: add c2c repo for gdal/libgdal-java
  apt_repository: repo="deb http://pkg.camptocamp.net/apt wheezy/staging sig-georchestra"

- name: install runtime dependencies
  apt: pkg={{ item }} state=installed default_release=staging
  with_items:
  - gdal-bin
  - libgdal-java

- name: point georchestra's shared.loader to catalina.base/shared/*.jar
  lineinfile:
    dest: "{{ tomcat_basedir }}/georchestra/conf/catalina.properties"
    regexp: 'shared.loader=${catalina.home}/shared/classes,${catalina.home}/shared/*.jar,/var/lib/tomcat6/shared/classes,/var/lib/tomcat6/shared/*.jar'
    line: 'shared.loader=${catalina.home}/shared/classes,${catalina.base}/shared/*.jar,/var/lib/tomcat6/shared/classes,/var/lib/tomcat6/shared/*.jar'

- name: create tomcat shared dir
  file: dest={{ tomcat_basedir }}/georchestra/shared/ state=directory

- name: symlink gdal.jar to tomcat shared dir
  file: src=/usr/share/java/gdal.jar dest={{ tomcat_basedir }}/georchestra/shared/gdal.jar state=link

- name: hardlink gdal.jar to geoserver libdir
  file: src=/usr/share/java/gdal.jar dest={{ tomcat_basedir }}/geoserver/webapps/geoserver/WEB-INF/lib/gdal.jar state=hard

- name: remove conflicting imageio-ext-gdal-bindings jar
  file: path={{ tomcat_basedir }}/geoserver/webapps/geoserver/WEB-INF/lib/imageio-ext-gda-bindings-1.9.2.jar state=absent
