- name: install apt-transport-https
  apt: pkg=apt-transport-https state=installed

- name: add georchestra repository key
  apt_key: url={{ georchestra_debian_key }}

- name: add georchestra debian repo
  apt_repository: repo={{ georchestra_debian_repo }}

- name: install debian packages
  apt: pkg={{ item.value.pkg }} default_release=jessie update_cache=yes state=latest
  with_dict: georchestra_wars

- name: symlink webapps in each tomcat instance
  file:
    owner: tomcat8
    src: "/usr/share/lib/{{ item.value.pkg }}/{{ item.key }}-generic.war"
    dest: "{{ tomcat_basedir }}/{{ item.value.tomcat }}/webapps/{{ item.key }}.war"
    state: link
  with_dict: georchestra_wars

# instances need to be started so that webapps are deployed
- name: start instances
  service: name=tomcat-{{ item }} state=started
  with_items: tomcat_instances.keys()
