- name: install apt-transport-https
  apt: pkg=apt-transport-https state=installed

- name: add georchestra repository key
  apt_key: url=https://build.georchestra.org/debian/build.georchestra.org.asc

- name: add georchestra debian repo
  apt_repository: repo="deb https://build.georchestra.org/debian jessie main"

- name: install debian packages
  apt: pkg={{ item.value.pkg }} default_release=jessie update_cache=yes state=latest
  with_dict: georchestra_wars

- name: symlink webapps in each tomcat instance
  file:
    owner: tomcat8
    src: "/usr/share/lib/{{ item.value.pkg }}/{{ item.key }}-generic.war"
    dest: "{{ tomcat_basedir }}/{{ item.value.tomcat }}/webapps/{{ item.key }}.war"
    state: link
  with_dict: georchestra_wars
