- name: install curl
  apt: pkg=curl state=installed

- name: fetch WARs
#  get_url:
#    dest: /tmp/{{item}}.war
#    validate_certs: no
#    url: https://sdi.georchestra.org/ci/job/georchestra-template/lastSuccessfulBuild/artifact/{{ item.url }}/target/{{ item.name }}-template.war
  command: >
    curl -o /tmp/{{ item.name }}.war https://sdi.georchestra.org/ci/job/georchestra-template/lastSuccessfulBuild/artifact/{{ item.url }}/target/{{ item.name }}-template.war
    creates=/tmp/{{ item.name }}.war
  with_items: georchestra_wars

- name: create destdir
  file: dest=/srv/tomcat/{{item.tomcat}}/webapps/{{ item.name }} owner=tomcat6 state=directory
  with_items: georchestra_wars

- name: unzip WARs
  sudo: yes
  sudo_user: tomcat6
  unarchive:
    src: /tmp/{{item.name}}.war
    dest: /srv/tomcat/{{item.tomcat}}/webapps/{{ item.name }}
    copy: no
    creates: /srv/tomcat/{{ item.tomcat }}/webapps/{{ item.name }}/WEB-INF
  with_items: georchestra_wars
