tomcat_basedir: /srv/tomcat
tomcat_instances: {
  proxycas: {
    port: 8180,
    control_port: 8105
  },
  geoserver: {
    port: 8280,
    control_port: 8205
  },
  georchestra: {
    port: 8380,
    control_port: 8305
  },
}
