other_schemas: [ mapfishapp, ldapadmin, downloadform, geofence, ogcstatistics ]
other_schemas_urls:
  - https://raw.github.com/georchestra/georchestra/master/mapfishapp/database.sql
  - https://raw.github.com/georchestra/georchestra/master/ldapadmin/database.sql
  - https://raw.github.com/georchestra/georchestra/master/downloadform/database.sql
  - https://raw.github.com/georchestra/geofence/georchestra/doc/setup/sql/002_create_schema_postgres.sql
  - https://raw.github.com/georchestra/georchestra/master/ogc-server-statistics/database.sql
cadastrapp_tmpdir: /tmp/cadastrappsql
cadastrapp_views : [
  { script: qgisCommune, view: commune },
  { script: qgisHabitationDetails, view: deschabitation },
  { script: qgisParcelle, view: parcelle },
  { script: qgisProprietaire, view: proprietaire },
  { script: qgisProprietaireParcelle, view: proprietaire_parcelle },
  { script: qgisProprieteBatie, view: proprietebatie },
  { script: qgisProprieteNonBatie, view: proprietenonbatie },
  { script: qgisSection, view: section } ]
cadastrapp_tables: [
  { script: groupe_autorisation, path: commun/user },
  { script: uf_parcelle, path: qgis/tables },
  { script: prop_ccodem, path: commun/tables },
  { script: prop_ccodro, path: commun/tables },
  { script: prop_ccoqua, path: commun/tables },
  { script: prop_ccogrm, path: commun/tables },
  { script: prop_dnatpr, path: commun/tables } ]
qadastre_dbhost: 10.0.0.9
qadastre_dbname: qadastre
qadastre_dbuser: qadastre
qadastre_dbpass: qadastre
qadastre_schema: qadastre
