- name: installing dependencies
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - tomcat6
  - tomcat6-user #needed for tomcat6-create-instance

- name: disable default instance
  service: name=tomcat6 state=stopped enabled=no

- name: create keystore
  command: >
    keytool -genkey -alias localhost \
      -keystore /etc/tomcat6/keystore \
      -storepass {{ tomcat_keystore_pass }} \
      -keypass {{ tomcat_keystore_pass }} \
      -keyalg RSA \
      -keysize 2048 \
      -dname "CN=localhost, O=IT, L=Somewhere, C=FR"
    creates=/etc/tomcat6/keystore

- name: create /srv/tomcat
  file: name=/srv/tomcat/ state=directory
