- name: georchestra deployment
  hosts: test
  sudo: yes
  roles:
    - georchestra
  vars:
    openldap_rootdn: cn=admin,dc=georchestra,dc=org
    openldap_rootpw: secret
    georchestra_fqdn: georchestra.demo.craig.fr
    georchestra_dbname: georchestra
    georchestra_dbuser: georchestra
    georchestra_dbpass: georchestra
    geonetwork_schema: geonetwork
    geonetwork_dbuser: geonetwork
    geonetwork_dbpass: geonetwork
    geonetwork_datadir: /srv/data/geonetwork/
    geoserver_privileged_user: geoserver_privileged_user
    geoserver_privileged_pass: geoserver_privileged_pass
    geoserver_datadir: /srv/data/geoserver/
    geowebcache_datadir: /srv/data/geowebcache/
    extractor_datadir: /srv/data/extractor/
    tomcat_keystore_pass: tomcatkstp
    tomcat_basedir: /srv/tomcat
    logs_basedir: /srv/logs
    tomcat_instances: {
      proxycas: { port: 8180, control_port: 8105 },
      geoserver: { port: 8280, control_port: 8205 },
      georchestra: { port: 8380, control_port: 8305 }
    }
    georchestra_wars: [
      { name: analytics, url: analytics, tomcat: georchestra },
      { name: cas, url: cas-server-webapp, tomcat: proxycas },
      { name: catalogapp, url: catalogapp, tomcat: georchestra },
      { name: downloadform, url: downloadform, tomcat: georchestra },
      { name: extractorapp, url: extractorapp, tomcat: georchestra },
      { name: geonetwork, url: geonetwork/web, tomcat: georchestra },
      { name: geoserver, url: geoserver/webapp, tomcat: geoserver },
      { name: geowebcache, url: geowebcache-webapp, tomcat: geoserver },
      { name: header, url: header, tomcat: georchestra },
      { name: ldapadmin, url: ldapadmin, tomcat: georchestra },
      { name: mapfishapp, url: mapfishapp, tomcat: georchestra },
      { name: ROOT, url: security-proxy, tomcat: proxycas }]
