- name: georchestra deployment
  hosts: test
  sudo: yes
  roles:
    - georchestra
  vars:
    openldap_rootdn: cn=admin,dc=georchestra,dc=org
    openldap_rootpw: secret
    georchestra_fqdn: georchestra.demo.craig.fr
    georchestra_dbname: georchestra
    georchestra_dbuser: georchestra
    georchestra_dbpass: georchestra
    geonetwork_schema: geonetwork
    geonetwork_dbuser: geonetwork
    geonetwork_dbpass: geonetwork
    geonetwork_datadir: /srv/data/geonetwork/
    geoserver_privileged_user: geoserver_privileged_user
    geoserver_privileged_pass: geoserver_privileged_pass
    geoserver_datadir: /srv/data/geoserver/
    geowebcache_datadir: /srv/data/geowebcache/
    extractor_datadir: /srv/data/extractor/
    tomcat_keystore_pass: tomcatkstp
    tomcat_basedir: /srv/tomcat
    logs_basedir: /srv/log
    ldapadmin_adminemail: admin@craig.fr
    tomcat_instances: {
      proxycas: { port: 8180, control_port: 8105 },
      geoserver: { port: 8280, control_port: 8205 },
      georchestra: { port: 8380, control_port: 8305 }
    }
    georchestra_wars: {
      analytics:{ url: analytics, tomcat: georchestra },
      cas:{ url: cas-server-webapp, tomcat: proxycas },
      catalogapp:{ url: catalogapp, tomcat: georchestra },
      downloadform:{ url: downloadform, tomcat: georchestra },
      extractorapp:{ url: extractorapp, tomcat: georchestra },
      geonetwork:{ url: geonetwork/web, tomcat: georchestra },
      geoserver:{ url: geoserver/webapp, tomcat: geoserver },
      geowebcache:{ url: geowebcache-webapp, tomcat: geoserver },
      header:{ url: header, tomcat: georchestra },
      ldapadmin:{ url: ldapadmin, tomcat: georchestra },
      mapfishapp:{ url: mapfishapp, tomcat: georchestra },
      ROOT:{ url: security-proxy, tomcat: proxycas }
    }
