- name: georchestra deployment
  hosts: test
  sudo: yes
  roles:
    - georchestra
  vars:
    openldap_basedn: dc=georchestra,dc=org
    openldap_rootdn: cn=admin,dc=georchestra,dc=org
    openldap_rootpw: secret
    georchestra_fqdn: georchestra.demo.craig.fr
    georchestra_dbname: georchestra
    georchestra_dbuser: georchestra
    georchestra_dbpass: georchestra
    georchestra_datadir: /etc/georchestra
    geonetwork_dbname: geonetwork
    geonetwork_dbuser: geonetwork
    geonetwork_dbpass: geonetwork
    geonetwork_datadir: /srv/data/geonetwork/
    geoserver_privileged_user: geoserver_privileged_user
    geoserver_privileged_pass: gerlsSnFd6SmM
    geoserver_datadir: /srv/data/geoserver/
    geoserver_wms_srslist: [2154, 3857, 3942, 3943, 3944, 3945, 3946, 3947, 3948, 3949, 3950, 4171, 4258, 4326, 23030, 23031, 23032, 32630, 32631, 32632, 4171, 4271, 3758]
    geowebcache_datadir: /srv/data/geowebcache/
    extractor_datadir: /srv/data/extractor/
    mapfishapp_datadir: /srv/data/mapfishapp/
    tomcat_keystore_pass: tomcatkstp
    tomcat_basedir: /srv/tomcat
    logs_basedir: /srv/log
    ldapadmin_adminemail: admin@craig.fr
    tomcat_instances: {
      proxycas: { port: 8180, control_port: 8105 },
      geoserver: { port: 8280, control_port: 8205 },
      georchestra: { port: 8380, control_port: 8305 }
    }
    georchestra_wars: {
      analytics: { pkg: georchestra-analytics,  tomcat: georchestra },
      cas: { pkg: georchestra-cas, tomcat: proxycas },
      catalogapp: { pkg: georchestra-catalogapp, tomcat: georchestra },
      extractorapp: { pkg: georchestra-extractorapp,  tomcat: georchestra },
      geonetwork: { pkg: georchestra-geonetwork3,  tomcat: georchestra },
      geoserver: { pkg: georchestra-geoserver, tomcat: geoserver },
      geowebcache: { pkg: georchestra-geowebcache, tomcat: georchestra },
      header: { pkg: georchestra-header, tomcat: georchestra },
      ldapadmin: { pkg: georchestra-ldapadmin, tomcat: georchestra },
      mapfishapp: { pkg: georchestra-mapfishapp, tomcat: georchestra },
      ROOT: { pkg: georchestra-security-proxy, tomcat: proxycas }
    }
