- name: georchestra deployment
  hosts: test
  sudo: yes
  roles:
    - georchestra
  vars:
    openldap_rootdn: cn=admin,dc=georchestra,dc=org
    openldap_rootpw: secret
    georchestra_fqdn: georchestra.demo.craig.fr
    georchestra_dbname: georchestra
    georchestra_dbuser: georchestra
    georchestra_dbpass: georchestra
    geonetwork_schema: geonetwork
    geonetwork_dbuser: geonetwork
    geonetwork_dbpass: geonetwork
    geonetwork_datadir: /srv/data/geonetwork/
    geoserver_privileged_user: geoserver_privileged_user
    geoserver_privileged_pass: geoserver_privileged_pass
    geoserver_datadir: /srv/data/geoserver/
    geowebcache_datadir: /srv/data/geowebcache/
    extractor_datadir: /srv/data/extractor/
    tomcat_keystore_pass: tomcatkstp
